# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Apr 25 22:48:32 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(707, 141)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ImagePy", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.drawRec = QtGui.QToolButton(self.centralwidget)
        self.drawRec.setMinimumSize(QtCore.QSize(35, 35))
        self.drawRec.setText(QtGui.QApplication.translate("MainWindow", "[]", None, QtGui.QApplication.UnicodeUTF8))
        self.drawRec.setObjectName(_fromUtf8("drawRec"))
        self.horizontalLayout.addWidget(self.drawRec)
        self.drawCirc = QtGui.QToolButton(self.centralwidget)
        self.drawCirc.setMinimumSize(QtCore.QSize(35, 35))
        self.drawCirc.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.drawCirc.setObjectName(_fromUtf8("drawCirc"))
        self.horizontalLayout.addWidget(self.drawCirc)
        self.drawPoly = QtGui.QToolButton(self.centralwidget)
        self.drawPoly.setMinimumSize(QtCore.QSize(35, 35))
        self.drawPoly.setText(QtGui.QApplication.translate("MainWindow", "{  }", None, QtGui.QApplication.UnicodeUTF8))
        self.drawPoly.setObjectName(_fromUtf8("drawPoly"))
        self.horizontalLayout.addWidget(self.drawPoly)
        self.drawLine = QtGui.QToolButton(self.centralwidget)
        self.drawLine.setMinimumSize(QtCore.QSize(35, 35))
        self.drawLine.setText(QtGui.QApplication.translate("MainWindow", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.drawLine.setObjectName(_fromUtf8("drawLine"))
        self.horizontalLayout.addWidget(self.drawLine)
        self.markPoint = QtGui.QToolButton(self.centralwidget)
        self.markPoint.setMinimumSize(QtCore.QSize(35, 35))
        self.markPoint.setText(QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.markPoint.setObjectName(_fromUtf8("markPoint"))
        self.horizontalLayout.addWidget(self.markPoint)
        self.zoom = QtGui.QToolButton(self.centralwidget)
        self.zoom.setMinimumSize(QtCore.QSize(35, 35))
        self.zoom.setText(QtGui.QApplication.translate("MainWindow", "=O", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom.setObjectName(_fromUtf8("zoom"))
        self.horizontalLayout.addWidget(self.zoom)
        self.toolButton_11 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_11.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_11.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.horizontalLayout.addWidget(self.toolButton_11)
        self.toolButton_13 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_13.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_13.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.horizontalLayout.addWidget(self.toolButton_13)
        self.toolButton_12 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_12.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_12.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_12.setObjectName(_fromUtf8("toolButton_12"))
        self.horizontalLayout.addWidget(self.toolButton_12)
        self.toolButton_8 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_8.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.horizontalLayout.addWidget(self.toolButton_8)
        self.toolButton_10 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_10.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_10.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.horizontalLayout.addWidget(self.toolButton_10)
        self.quit = QtGui.QToolButton(self.centralwidget)
        self.quit.setMinimumSize(QtCore.QSize(35, 35))
        self.quit.setText(QtGui.QApplication.translate("MainWindow", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setObjectName(_fromUtf8("quit"))
        self.horizontalLayout.addWidget(self.quit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuProcess = QtGui.QMenu(self.menubar)
        self.menuProcess.setTitle(QtGui.QApplication.translate("MainWindow", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProcess.setObjectName(_fromUtf8("menuProcess"))
        self.menuPlugins = QtGui.QMenu(self.menubar)
        self.menuPlugins.setTitle(QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAdjust = QtGui.QMenu(self.menuEdit)
        self.menuAdjust.setTitle(QtGui.QApplication.translate("MainWindow", "Adjust", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdjust.setObjectName(_fromUtf8("menuAdjust"))
        self.menuType = QtGui.QMenu(self.menuEdit)
        self.menuType.setTitle(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.menuType.setObjectName(_fromUtf8("menuType"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionCrop = QtGui.QAction(MainWindow)
        self.actionCrop.setText(QtGui.QApplication.translate("MainWindow", "Crop   Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCrop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCrop.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionCrop.setObjectName(_fromUtf8("actionCrop"))
        self.actionBALM = QtGui.QAction(MainWindow)
        self.actionBALM.setText(QtGui.QApplication.translate("MainWindow", "BALM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBALM.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionBALM.setObjectName(_fromUtf8("actionBALM"))
        self.actionTrackObject = QtGui.QAction(MainWindow)
        self.actionTrackObject.setText(QtGui.QApplication.translate("MainWindow", "Track Object", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTrackObject.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionTrackObject.setObjectName(_fromUtf8("actionTrackObject"))
        self.actionFitGaussian = QtGui.QAction(MainWindow)
        self.actionFitGaussian.setText(QtGui.QApplication.translate("MainWindow", "Fit Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitGaussian.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionFitGaussian.setObjectName(_fromUtf8("actionFitGaussian"))
        self.actionManagePlugins = QtGui.QAction(MainWindow)
        self.actionManagePlugins.setText(QtGui.QApplication.translate("MainWindow", "Manage Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManagePlugins.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionManagePlugins.setObjectName(_fromUtf8("actionManagePlugins"))
        self.actionIntensityProfile = QtGui.QAction(MainWindow)
        self.actionIntensityProfile.setText(QtGui.QApplication.translate("MainWindow", "Intensity Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntensityProfile.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionIntensityProfile.setObjectName(_fromUtf8("actionIntensityProfile"))
        self.actionResults = QtGui.QAction(MainWindow)
        self.actionResults.setText(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResults.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionResults.setObjectName(_fromUtf8("actionResults"))
        self.actionBritnessContrast = QtGui.QAction(MainWindow)
        self.actionBritnessContrast.setText(QtGui.QApplication.translate("MainWindow", "&Britness/Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBritnessContrast.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBritnessContrast.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionBritnessContrast.setObjectName(_fromUtf8("actionBritnessContrast"))
        self.actionThreshhold = QtGui.QAction(MainWindow)
        self.actionThreshhold.setText(QtGui.QApplication.translate("MainWindow", "Threshhold", None, QtGui.QApplication.UnicodeUTF8))
        self.actionThreshhold.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionThreshhold.setObjectName(_fromUtf8("actionThreshhold"))
        self.action8bit = QtGui.QAction(MainWindow)
        self.action8bit.setText(QtGui.QApplication.translate("MainWindow", "8 bit", None, QtGui.QApplication.UnicodeUTF8))
        self.action8bit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action8bit.setObjectName(_fromUtf8("action8bit"))
        self.action16bit = QtGui.QAction(MainWindow)
        self.action16bit.setText(QtGui.QApplication.translate("MainWindow", "16 bit", None, QtGui.QApplication.UnicodeUTF8))
        self.action16bit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action16bit.setObjectName(_fromUtf8("action16bit"))
        self.actionGaussBlur = QtGui.QAction(MainWindow)
        self.actionGaussBlur.setText(QtGui.QApplication.translate("MainWindow", "GaussBlur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGaussBlur.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionGaussBlur.setObjectName(_fromUtf8("actionGaussBlur"))
        self.actionDuplicate = QtGui.QAction(MainWindow)
        self.actionDuplicate.setText(QtGui.QApplication.translate("MainWindow", "&Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicate.setObjectName(_fromUtf8("actionDuplicate"))
        self.actionInvert = QtGui.QAction(MainWindow)
        self.actionInvert.setText(QtGui.QApplication.translate("MainWindow", "&Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I, Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvert.setObjectName(_fromUtf8("actionInvert"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuProcess.addAction(self.actionResults)
        self.menuProcess.addAction(self.actionGaussBlur)
        self.menuPlugins.addAction(self.actionBALM)
        self.menuPlugins.addAction(self.actionTrackObject)
        self.menuPlugins.addAction(self.actionFitGaussian)
        self.menuPlugins.addAction(self.actionManagePlugins)
        self.menuAdjust.addAction(self.actionBritnessContrast)
        self.menuAdjust.addAction(self.actionThreshhold)
        self.menuType.addAction(self.action8bit)
        self.menuType.addAction(self.action16bit)
        self.menuEdit.addAction(self.menuType.menuAction())
        self.menuEdit.addAction(self.menuAdjust.menuAction())
        self.menuEdit.addAction(self.actionCrop)
        self.menuEdit.addAction(self.actionDuplicate)
        self.menuEdit.addAction(self.actionInvert)
        self.menuEdit.addAction(self.actionZoom)
        self.menuEdit.addAction(self.actionIntensityProfile)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProcess.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.quit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

